package com.example.model;

public class Company {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column datastorage..company.id
     *
     * @abatorgenerated Sun Apr 27 20:07:51 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column datastorage..company.companyname
     *
     * @abatorgenerated Sun Apr 27 20:07:51 CST 2014
     */
    private String companyname;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column datastorage..company.companycode
     *
     * @abatorgenerated Sun Apr 27 20:07:51 CST 2014
     */
    private String companycode;

   

    public Company(Integer id, String companyname, String companycode) {	
		this.id = id;
		this.companyname = companyname;
		this.companycode = companycode;
	}



	/**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column datastorage..company.id
     *
     * @return the value of datastorage..company.id
     *
     * @abatorgenerated Sun Apr 27 20:07:51 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column datastorage..company.id
     *
     * @param id the value for datastorage..company.id
     *
     * @abatorgenerated Sun Apr 27 20:07:51 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column datastorage..company.companyname
     *
     * @return the value of datastorage..company.companyname
     *
     * @abatorgenerated Sun Apr 27 20:07:51 CST 2014
     */
    public String getCompanyname() {
        return companyname;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column datastorage..company.companyname
     *
     * @param companyname the value for datastorage..company.companyname
     *
     * @abatorgenerated Sun Apr 27 20:07:51 CST 2014
     */
    public void setCompanyname(String companyname) {
        this.companyname = companyname;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column datastorage..company.companycode
     *
     * @return the value of datastorage..company.companycode
     *
     * @abatorgenerated Sun Apr 27 20:07:51 CST 2014
     */
    public String getCompanycode() {
        return companycode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column datastorage..company.companycode
     *
     * @param companycode the value for datastorage..company.companycode
     *
     * @abatorgenerated Sun Apr 27 20:07:51 CST 2014
     */
    public void setCompanycode(String companycode) {
        this.companycode = companycode;
    }
}