package com.example.model;

public class Traget {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column datastorage..traget.id
     *
     * @abatorgenerated Sun Apr 27 20:07:51 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column datastorage..traget.userid
     *
     * @abatorgenerated Sun Apr 27 20:07:51 CST 2014
     */
    private Integer userid;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column datastorage..traget.companyid
     *
     * @abatorgenerated Sun Apr 27 20:07:51 CST 2014
     */
    private Integer companyid;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column datastorage..traget.tragetname
     *
     * @abatorgenerated Sun Apr 27 20:07:51 CST 2014
     */
    private String tragetname;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column datastorage..traget.tragetvalue
     *
     * @abatorgenerated Sun Apr 27 20:07:51 CST 2014
     */
    private String tragetvalue;

    
    public Traget(Integer id, Integer userid, Integer companyid,
			String tragetname, String tragetvalue) {
		super();
		this.id = id;
		this.userid = userid;
		this.companyid = companyid;
		this.tragetname = tragetname;
		this.tragetvalue = tragetvalue;
	}

	/**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column datastorage..traget.id
     *
     * @return the value of datastorage..traget.id
     *
     * @abatorgenerated Sun Apr 27 20:07:51 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column datastorage..traget.id
     *
     * @param id the value for datastorage..traget.id
     *
     * @abatorgenerated Sun Apr 27 20:07:51 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column datastorage..traget.userid
     *
     * @return the value of datastorage..traget.userid
     *
     * @abatorgenerated Sun Apr 27 20:07:51 CST 2014
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column datastorage..traget.userid
     *
     * @param userid the value for datastorage..traget.userid
     *
     * @abatorgenerated Sun Apr 27 20:07:51 CST 2014
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column datastorage..traget.companyid
     *
     * @return the value of datastorage..traget.companyid
     *
     * @abatorgenerated Sun Apr 27 20:07:51 CST 2014
     */
    public Integer getCompanyid() {
        return companyid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column datastorage..traget.companyid
     *
     * @param companyid the value for datastorage..traget.companyid
     *
     * @abatorgenerated Sun Apr 27 20:07:51 CST 2014
     */
    public void setCompanyid(Integer companyid) {
        this.companyid = companyid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column datastorage..traget.tragetname
     *
     * @return the value of datastorage..traget.tragetname
     *
     * @abatorgenerated Sun Apr 27 20:07:51 CST 2014
     */
    public String getTragetname() {
        return tragetname;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column datastorage..traget.tragetname
     *
     * @param tragetname the value for datastorage..traget.tragetname
     *
     * @abatorgenerated Sun Apr 27 20:07:51 CST 2014
     */
    public void setTragetname(String tragetname) {
        this.tragetname = tragetname;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column datastorage..traget.tragetvalue
     *
     * @return the value of datastorage..traget.tragetvalue
     *
     * @abatorgenerated Sun Apr 27 20:07:51 CST 2014
     */
    public String getTragetvalue() {
        return tragetvalue;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column datastorage..traget.tragetvalue
     *
     * @param tragetvalue the value for datastorage..traget.tragetvalue
     *
     * @abatorgenerated Sun Apr 27 20:07:51 CST 2014
     */
    public void setTragetvalue(String tragetvalue) {
        this.tragetvalue = tragetvalue;
    }
}