package com.example.model;

public class UserQcCc {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column datastorage..user_qc_cc.id
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column datastorage..user_qc_cc.userid
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    private Integer userid;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column datastorage..user_qc_cc.companycode
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    private Integer companycode;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column datastorage..user_qc_cc.srcAddr
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    private String srcaddr;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column datastorage..user_qc_cc.destAddr
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    private String destaddr;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column datastorage..user_qc_cc.startdate
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    private String startdate;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column datastorage..user_qc_cc.enddate
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    private String enddate;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column datastorage..user_qc_cc.memo
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    private String memo;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column datastorage..user_qc_cc.adddate
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    private String adddate;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column datastorage..user_qc_cc.id
     *
     * @return the value of datastorage..user_qc_cc.id
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column datastorage..user_qc_cc.id
     *
     * @param id the value for datastorage..user_qc_cc.id
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column datastorage..user_qc_cc.userid
     *
     * @return the value of datastorage..user_qc_cc.userid
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column datastorage..user_qc_cc.userid
     *
     * @param userid the value for datastorage..user_qc_cc.userid
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column datastorage..user_qc_cc.companycode
     *
     * @return the value of datastorage..user_qc_cc.companycode
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    public Integer getCompanycode() {
        return companycode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column datastorage..user_qc_cc.companycode
     *
     * @param companycode the value for datastorage..user_qc_cc.companycode
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    public void setCompanycode(Integer companycode) {
        this.companycode = companycode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column datastorage..user_qc_cc.srcAddr
     *
     * @return the value of datastorage..user_qc_cc.srcAddr
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    public String getSrcaddr() {
        return srcaddr;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column datastorage..user_qc_cc.srcAddr
     *
     * @param srcaddr the value for datastorage..user_qc_cc.srcAddr
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    public void setSrcaddr(String srcaddr) {
        this.srcaddr = srcaddr;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column datastorage..user_qc_cc.destAddr
     *
     * @return the value of datastorage..user_qc_cc.destAddr
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    public String getDestaddr() {
        return destaddr;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column datastorage..user_qc_cc.destAddr
     *
     * @param destaddr the value for datastorage..user_qc_cc.destAddr
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    public void setDestaddr(String destaddr) {
        this.destaddr = destaddr;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column datastorage..user_qc_cc.startdate
     *
     * @return the value of datastorage..user_qc_cc.startdate
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    public String getStartdate() {
        return startdate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column datastorage..user_qc_cc.startdate
     *
     * @param startdate the value for datastorage..user_qc_cc.startdate
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    public void setStartdate(String startdate) {
        this.startdate = startdate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column datastorage..user_qc_cc.enddate
     *
     * @return the value of datastorage..user_qc_cc.enddate
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    public String getEnddate() {
        return enddate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column datastorage..user_qc_cc.enddate
     *
     * @param enddate the value for datastorage..user_qc_cc.enddate
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    public void setEnddate(String enddate) {
        this.enddate = enddate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column datastorage..user_qc_cc.memo
     *
     * @return the value of datastorage..user_qc_cc.memo
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column datastorage..user_qc_cc.memo
     *
     * @param memo the value for datastorage..user_qc_cc.memo
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    public void setMemo(String memo) {
        this.memo = memo;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column datastorage..user_qc_cc.adddate
     *
     * @return the value of datastorage..user_qc_cc.adddate
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    public String getAdddate() {
        return adddate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column datastorage..user_qc_cc.adddate
     *
     * @param adddate the value for datastorage..user_qc_cc.adddate
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    public void setAdddate(String adddate) {
        this.adddate = adddate;
    }
	public UserQcCc() {
	}
	public UserQcCc(int id, int userid, int companycode,
			String srcaddr, String destaddr, String startdate, String enddate,
			String memo, String adddate) {
		super();
		this.id = id;
		this.userid = userid;
		this.companycode = companycode;
		this.srcaddr = srcaddr;
		this.destaddr = destaddr;
		this.startdate = startdate;
		this.enddate = enddate;
		this.memo = memo;
		this.adddate = adddate;
	}
    
}