package com.example.model;

public class UserQcDk {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column datastorage..user_qc_dk.id
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column datastorage..user_qc_dk.userid
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    private Integer userid;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column datastorage..user_qc_dk.companycode
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    private Integer companycode;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column datastorage..user_qc_dk.type
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    private Integer type;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column datastorage..user_qc_dk.address
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    private String address;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column datastorage..user_qc_dk.addresspoint
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    private String addresspoint;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column datastorage..user_qc_dk.memo
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    private String memo;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column datastorage..user_qc_dk.adddate
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    private String adddate;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column datastorage..user_qc_dk.id
     *
     * @return the value of datastorage..user_qc_dk.id
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column datastorage..user_qc_dk.id
     *
     * @param id the value for datastorage..user_qc_dk.id
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column datastorage..user_qc_dk.userid
     *
     * @return the value of datastorage..user_qc_dk.userid
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column datastorage..user_qc_dk.userid
     *
     * @param userid the value for datastorage..user_qc_dk.userid
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column datastorage..user_qc_dk.companycode
     *
     * @return the value of datastorage..user_qc_dk.companycode
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    public Integer getCompanycode() {
        return companycode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column datastorage..user_qc_dk.companycode
     *
     * @param companycode the value for datastorage..user_qc_dk.companycode
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    public void setCompanycode(Integer companycode) {
        this.companycode = companycode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column datastorage..user_qc_dk.type
     *
     * @return the value of datastorage..user_qc_dk.type
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column datastorage..user_qc_dk.type
     *
     * @param type the value for datastorage..user_qc_dk.type
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column datastorage..user_qc_dk.address
     *
     * @return the value of datastorage..user_qc_dk.address
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column datastorage..user_qc_dk.address
     *
     * @param address the value for datastorage..user_qc_dk.address
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column datastorage..user_qc_dk.addresspoint
     *
     * @return the value of datastorage..user_qc_dk.addresspoint
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    public String getAddresspoint() {
        return addresspoint;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column datastorage..user_qc_dk.addresspoint
     *
     * @param addresspoint the value for datastorage..user_qc_dk.addresspoint
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    public void setAddresspoint(String addresspoint) {
        this.addresspoint = addresspoint;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column datastorage..user_qc_dk.memo
     *
     * @return the value of datastorage..user_qc_dk.memo
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column datastorage..user_qc_dk.memo
     *
     * @param memo the value for datastorage..user_qc_dk.memo
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    public void setMemo(String memo) {
        this.memo = memo;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column datastorage..user_qc_dk.adddate
     *
     * @return the value of datastorage..user_qc_dk.adddate
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    public String getAdddate() {
        return adddate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column datastorage..user_qc_dk.adddate
     *
     * @param adddate the value for datastorage..user_qc_dk.adddate
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    public void setAdddate(String adddate) {
        this.adddate = adddate;
    }

	public UserQcDk(Integer id, Integer userid, Integer companycode,
			Integer type, String address, String addresspoint, String memo,
			String adddate) {
		super();
		this.id = id;
		this.userid = userid;
		this.companycode = companycode;
		this.type = type;
		this.address = address;
		this.addresspoint = addresspoint;
		this.memo = memo;
		this.adddate = adddate;
	}
    
    
}