package com.example.model;

public class UserQcWc {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column datastorage..user_qc_wc.id
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column datastorage..user_qc_wc.userid
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    private Integer userid;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column datastorage..user_qc_wc.companycode
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    private Integer companycode;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column datastorage..user_qc_wc.startdate
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    private String startdate;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column datastorage..user_qc_wc.starttime
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    private String starttime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column datastorage..user_qc_wc.endtime
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    private String endtime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column datastorage..user_qc_wc.memo
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    private String memo;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column datastorage..user_qc_wc.adddate
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    private String adddate;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column datastorage..user_qc_wc.id
     *
     * @return the value of datastorage..user_qc_wc.id
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column datastorage..user_qc_wc.id
     *
     * @param id the value for datastorage..user_qc_wc.id
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column datastorage..user_qc_wc.userid
     *
     * @return the value of datastorage..user_qc_wc.userid
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column datastorage..user_qc_wc.userid
     *
     * @param userid the value for datastorage..user_qc_wc.userid
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column datastorage..user_qc_wc.companycode
     *
     * @return the value of datastorage..user_qc_wc.companycode
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    public Integer getCompanycode() {
        return companycode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column datastorage..user_qc_wc.companycode
     *
     * @param companycode the value for datastorage..user_qc_wc.companycode
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    public void setCompanycode(Integer companycode) {
        this.companycode = companycode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column datastorage..user_qc_wc.startdate
     *
     * @return the value of datastorage..user_qc_wc.startdate
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    public String getStartdate() {
        return startdate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column datastorage..user_qc_wc.startdate
     *
     * @param startdate the value for datastorage..user_qc_wc.startdate
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    public void setStartdate(String startdate) {
        this.startdate = startdate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column datastorage..user_qc_wc.starttime
     *
     * @return the value of datastorage..user_qc_wc.starttime
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    public String getStarttime() {
        return starttime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column datastorage..user_qc_wc.starttime
     *
     * @param starttime the value for datastorage..user_qc_wc.starttime
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    public void setStarttime(String starttime) {
        this.starttime = starttime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column datastorage..user_qc_wc.endtime
     *
     * @return the value of datastorage..user_qc_wc.endtime
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    public String getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column datastorage..user_qc_wc.endtime
     *
     * @param endtime the value for datastorage..user_qc_wc.endtime
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    public void setEndtime(String endtime) {
        this.endtime = endtime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column datastorage..user_qc_wc.memo
     *
     * @return the value of datastorage..user_qc_wc.memo
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column datastorage..user_qc_wc.memo
     *
     * @param memo the value for datastorage..user_qc_wc.memo
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    public void setMemo(String memo) {
        this.memo = memo;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column datastorage..user_qc_wc.adddate
     *
     * @return the value of datastorage..user_qc_wc.adddate
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    public String getAdddate() {
        return adddate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column datastorage..user_qc_wc.adddate
     *
     * @param adddate the value for datastorage..user_qc_wc.adddate
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    public void setAdddate(String adddate) {
        this.adddate = adddate;
    }

	public UserQcWc(Integer id, Integer userid, Integer companycode,
			String startdate, String starttime, String endtime, String memo,
			String adddate) {
		super();
		this.id = id;
		this.userid = userid;
		this.companycode = companycode;
		this.startdate = startdate;
		this.starttime = starttime;
		this.endtime = endtime;
		this.memo = memo;
		this.adddate = adddate;
	}
    
    
}