package com.example.model;

public class UserQcQj {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column datastorage..user_qc_qj.id
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column datastorage..user_qc_qj.userid
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    private Integer userid;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column datastorage..user_qc_qj.companycode
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    private Integer companycode;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column datastorage..user_qc_qj.startdate
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    private String startdate;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column datastorage..user_qc_qj.starttime
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    private String starttime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column datastorage..user_qc_qj.enddate
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    private String enddate;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column datastorage..user_qc_qj.endtime
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    private String endtime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column datastorage..user_qc_qj.days
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    private String days;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column datastorage..user_qc_qj.type
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    private String type;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column datastorage..user_qc_qj.memo
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    private String memo;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column datastorage..user_qc_qj.adddate
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    private String adddate;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column datastorage..user_qc_qj.id
     *
     * @return the value of datastorage..user_qc_qj.id
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column datastorage..user_qc_qj.id
     *
     * @param id the value for datastorage..user_qc_qj.id
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column datastorage..user_qc_qj.userid
     *
     * @return the value of datastorage..user_qc_qj.userid
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column datastorage..user_qc_qj.userid
     *
     * @param userid the value for datastorage..user_qc_qj.userid
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column datastorage..user_qc_qj.companycode
     *
     * @return the value of datastorage..user_qc_qj.companycode
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    public Integer getCompanycode() {
        return companycode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column datastorage..user_qc_qj.companycode
     *
     * @param companycode the value for datastorage..user_qc_qj.companycode
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    public void setCompanycode(Integer companycode) {
        this.companycode = companycode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column datastorage..user_qc_qj.startdate
     *
     * @return the value of datastorage..user_qc_qj.startdate
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    public String getStartdate() {
        return startdate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column datastorage..user_qc_qj.startdate
     *
     * @param startdate the value for datastorage..user_qc_qj.startdate
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    public void setStartdate(String startdate) {
        this.startdate = startdate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column datastorage..user_qc_qj.starttime
     *
     * @return the value of datastorage..user_qc_qj.starttime
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    public String getStarttime() {
        return starttime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column datastorage..user_qc_qj.starttime
     *
     * @param starttime the value for datastorage..user_qc_qj.starttime
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    public void setStarttime(String starttime) {
        this.starttime = starttime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column datastorage..user_qc_qj.enddate
     *
     * @return the value of datastorage..user_qc_qj.enddate
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    public String getEnddate() {
        return enddate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column datastorage..user_qc_qj.enddate
     *
     * @param enddate the value for datastorage..user_qc_qj.enddate
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    public void setEnddate(String enddate) {
        this.enddate = enddate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column datastorage..user_qc_qj.endtime
     *
     * @return the value of datastorage..user_qc_qj.endtime
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    public String getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column datastorage..user_qc_qj.endtime
     *
     * @param endtime the value for datastorage..user_qc_qj.endtime
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    public void setEndtime(String endtime) {
        this.endtime = endtime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column datastorage..user_qc_qj.days
     *
     * @return the value of datastorage..user_qc_qj.days
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    public String getDays() {
        return days;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column datastorage..user_qc_qj.days
     *
     * @param days the value for datastorage..user_qc_qj.days
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    public void setDays(String days) {
        this.days = days;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column datastorage..user_qc_qj.type
     *
     * @return the value of datastorage..user_qc_qj.type
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column datastorage..user_qc_qj.type
     *
     * @param type the value for datastorage..user_qc_qj.type
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column datastorage..user_qc_qj.memo
     *
     * @return the value of datastorage..user_qc_qj.memo
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column datastorage..user_qc_qj.memo
     *
     * @param memo the value for datastorage..user_qc_qj.memo
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    public void setMemo(String memo) {
        this.memo = memo;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column datastorage..user_qc_qj.adddate
     *
     * @return the value of datastorage..user_qc_qj.adddate
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    public String getAdddate() {
        return adddate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column datastorage..user_qc_qj.adddate
     *
     * @param adddate the value for datastorage..user_qc_qj.adddate
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    public void setAdddate(String adddate) {
        this.adddate = adddate;
    }

	public UserQcQj(Integer id, Integer userid, Integer companycode,
			String startdate, String starttime, String enddate, String endtime,
			String days, String type, String memo, String adddate) {
		super();
		this.id = id;
		this.userid = userid;
		this.companycode = companycode;
		this.startdate = startdate;
		this.starttime = starttime;
		this.enddate = enddate;
		this.endtime = endtime;
		this.days = days;
		this.type = type;
		this.memo = memo;
		this.adddate = adddate;
	}
    
}