package com.example.model;
public class UserTask {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column datastorage..user_task.id
     *
     * @abatorgenerated Sat May 03 19:12:45 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column datastorage..user_task.userid
     *
     * @abatorgenerated Sat May 03 19:12:45 CST 2014
     */
    private Integer userid;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column datastorage..user_task.companycode
     *
     * @abatorgenerated Sat May 03 19:12:45 CST 2014
     */
    private Integer companycode;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column datastorage..user_task.tasklevel
     *
     * @abatorgenerated Sat May 03 19:12:45 CST 2014
     */
    private String tasklevel;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column datastorage..user_task.workuserid
     *
     * @abatorgenerated Sat May 03 19:12:45 CST 2014
     */
    private String workuserid;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column datastorage..user_task.task
     *
     * @abatorgenerated Sat May 03 19:12:45 CST 2014
     */
    private String task;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column datastorage..user_task.finshdate
     *
     * @abatorgenerated Sat May 03 19:12:45 CST 2014
     */
    private String finshdate;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column datastorage..user_task.status
     *
     * @abatorgenerated Sat May 03 19:12:45 CST 2014
     */
    private Integer status;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column datastorage..user_task.adddate
     *
     * @abatorgenerated Sat May 03 19:12:45 CST 2014
     */
    private String adddate;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column datastorage..user_task.id
     *
     * @return the value of datastorage..user_task.id
     *
     * @abatorgenerated Sat May 03 19:12:45 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column datastorage..user_task.id
     *
     * @param id the value for datastorage..user_task.id
     *
     * @abatorgenerated Sat May 03 19:12:45 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column datastorage..user_task.userid
     *
     * @return the value of datastorage..user_task.userid
     *
     * @abatorgenerated Sat May 03 19:12:45 CST 2014
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column datastorage..user_task.userid
     *
     * @param userid the value for datastorage..user_task.userid
     *
     * @abatorgenerated Sat May 03 19:12:45 CST 2014
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column datastorage..user_task.companycode
     *
     * @return the value of datastorage..user_task.companycode
     *
     * @abatorgenerated Sat May 03 19:12:45 CST 2014
     */
    public Integer getCompanycode() {
        return companycode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column datastorage..user_task.companycode
     *
     * @param companycode the value for datastorage..user_task.companycode
     *
     * @abatorgenerated Sat May 03 19:12:45 CST 2014
     */
    public void setCompanycode(Integer companycode) {
        this.companycode = companycode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column datastorage..user_task.tasklevel
     *
     * @return the value of datastorage..user_task.tasklevel
     *
     * @abatorgenerated Sat May 03 19:12:45 CST 2014
     */
    public String getTasklevel() {
        return tasklevel;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column datastorage..user_task.tasklevel
     *
     * @param tasklevel the value for datastorage..user_task.tasklevel
     *
     * @abatorgenerated Sat May 03 19:12:45 CST 2014
     */
    public void setTasklevel(String tasklevel) {
        this.tasklevel = tasklevel;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column datastorage..user_task.workuserid
     *
     * @return the value of datastorage..user_task.workuserid
     *
     * @abatorgenerated Sat May 03 19:12:45 CST 2014
     */
    public String getWorkuserid() {
        return workuserid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column datastorage..user_task.workuserid
     *
     * @param workuserid the value for datastorage..user_task.workuserid
     *
     * @abatorgenerated Sat May 03 19:12:45 CST 2014
     */
    public void setWorkuserid(String workuserid) {
        this.workuserid = workuserid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column datastorage..user_task.task
     *
     * @return the value of datastorage..user_task.task
     *
     * @abatorgenerated Sat May 03 19:12:45 CST 2014
     */
    public String getTask() {
        return task;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column datastorage..user_task.task
     *
     * @param task the value for datastorage..user_task.task
     *
     * @abatorgenerated Sat May 03 19:12:45 CST 2014
     */
    public void setTask(String task) {
        this.task = task;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column datastorage..user_task.finshdate
     *
     * @return the value of datastorage..user_task.finshdate
     *
     * @abatorgenerated Sat May 03 19:12:45 CST 2014
     */
    public String getFinshdate() {
        return finshdate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column datastorage..user_task.finshdate
     *
     * @param finshdate the value for datastorage..user_task.finshdate
     *
     * @abatorgenerated Sat May 03 19:12:45 CST 2014
     */
    public void setFinshdate(String finshdate) {
        this.finshdate = finshdate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column datastorage..user_task.status
     *
     * @return the value of datastorage..user_task.status
     *
     * @abatorgenerated Sat May 03 19:12:45 CST 2014
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column datastorage..user_task.status
     *
     * @param status the value for datastorage..user_task.status
     *
     * @abatorgenerated Sat May 03 19:12:45 CST 2014
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column datastorage..user_task.adddate
     *
     * @return the value of datastorage..user_task.adddate
     *
     * @abatorgenerated Sat May 03 19:12:45 CST 2014
     */
    public String getAdddate() {
        return adddate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column datastorage..user_task.adddate
     *
     * @param adddate the value for datastorage..user_task.adddate
     *
     * @abatorgenerated Sat May 03 19:12:45 CST 2014
     */
    public void setAdddate(String adddate) {
        this.adddate = adddate;
    }

	public UserTask(Integer id, Integer userid, Integer companycode,
			String tasklevel, String workuserid, String task, String finshdate,
			Integer status, String adddate) {
		super();
		this.id = id;
		this.userid = userid;
		this.companycode = companycode;
		this.tasklevel = tasklevel;
		this.workuserid = workuserid;
		this.task = task;
		this.finshdate = finshdate;
		this.status = status;
		this.adddate = adddate;
	}
    
    
}