package com.example.model;

public class Userpoints {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column datastorage..userpoints.id
     *
     * @abatorgenerated Sun Apr 27 20:07:51 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column datastorage..userpoints.username
     *
     * @abatorgenerated Sun Apr 27 20:07:51 CST 2014
     */
    private String username;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column datastorage..userpoints.point
     *
     * @abatorgenerated Sun Apr 27 20:07:51 CST 2014
     */
    private String point;

    
    
    public Userpoints(Integer id, String username, String point) {
		super();
		this.id = id;
		this.username = username;
		this.point = point;
	}

	/**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column datastorage..userpoints.id
     *
     * @return the value of datastorage..userpoints.id
     *
     * @abatorgenerated Sun Apr 27 20:07:51 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column datastorage..userpoints.id
     *
     * @param id the value for datastorage..userpoints.id
     *
     * @abatorgenerated Sun Apr 27 20:07:51 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column datastorage..userpoints.username
     *
     * @return the value of datastorage..userpoints.username
     *
     * @abatorgenerated Sun Apr 27 20:07:51 CST 2014
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column datastorage..userpoints.username
     *
     * @param username the value for datastorage..userpoints.username
     *
     * @abatorgenerated Sun Apr 27 20:07:51 CST 2014
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column datastorage..userpoints.point
     *
     * @return the value of datastorage..userpoints.point
     *
     * @abatorgenerated Sun Apr 27 20:07:51 CST 2014
     */
    public String getPoint() {
        return point;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column datastorage..userpoints.point
     *
     * @param point the value for datastorage..userpoints.point
     *
     * @abatorgenerated Sun Apr 27 20:07:51 CST 2014
     */
    public void setPoint(String point) {
        this.point = point;
    }
}