package com.example.model;

public class UserQcJb {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column datastorage..user_qc_jb.id
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column datastorage..user_qc_jb.userid
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    private Integer userid;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column datastorage..user_qc_jb.companycode
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    private Integer companycode;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column datastorage..user_qc_jb.stardate
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    private String stardate;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column datastorage..user_qc_jb.enddate
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    private String enddate;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column datastorage..user_qc_jb.starttime
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    private String starttime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column datastorage..user_qc_jb.endtime
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    private String endtime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column datastorage..user_qc_jb.costtime
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    private String costtime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column datastorage..user_qc_jb.memo
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    private String memo;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column datastorage..user_qc_jb.adddate
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    private String adddate;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column datastorage..user_qc_jb.id
     *
     * @return the value of datastorage..user_qc_jb.id
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column datastorage..user_qc_jb.id
     *
     * @param id the value for datastorage..user_qc_jb.id
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column datastorage..user_qc_jb.userid
     *
     * @return the value of datastorage..user_qc_jb.userid
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column datastorage..user_qc_jb.userid
     *
     * @param userid the value for datastorage..user_qc_jb.userid
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column datastorage..user_qc_jb.companycode
     *
     * @return the value of datastorage..user_qc_jb.companycode
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    public Integer getCompanycode() {
        return companycode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column datastorage..user_qc_jb.companycode
     *
     * @param companycode the value for datastorage..user_qc_jb.companycode
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    public void setCompanycode(Integer companycode) {
        this.companycode = companycode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column datastorage..user_qc_jb.stardate
     *
     * @return the value of datastorage..user_qc_jb.stardate
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    public String getStardate() {
        return stardate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column datastorage..user_qc_jb.stardate
     *
     * @param stardate the value for datastorage..user_qc_jb.stardate
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    public void setStardate(String stardate) {
        this.stardate = stardate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column datastorage..user_qc_jb.enddate
     *
     * @return the value of datastorage..user_qc_jb.enddate
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    public String getEnddate() {
        return enddate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column datastorage..user_qc_jb.enddate
     *
     * @param enddate the value for datastorage..user_qc_jb.enddate
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    public void setEnddate(String enddate) {
        this.enddate = enddate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column datastorage..user_qc_jb.starttime
     *
     * @return the value of datastorage..user_qc_jb.starttime
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    public String getStarttime() {
        return starttime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column datastorage..user_qc_jb.starttime
     *
     * @param starttime the value for datastorage..user_qc_jb.starttime
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    public void setStarttime(String starttime) {
        this.starttime = starttime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column datastorage..user_qc_jb.endtime
     *
     * @return the value of datastorage..user_qc_jb.endtime
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    public String getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column datastorage..user_qc_jb.endtime
     *
     * @param endtime the value for datastorage..user_qc_jb.endtime
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    public void setEndtime(String endtime) {
        this.endtime = endtime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column datastorage..user_qc_jb.costtime
     *
     * @return the value of datastorage..user_qc_jb.costtime
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    public String getCosttime() {
        return costtime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column datastorage..user_qc_jb.costtime
     *
     * @param costtime the value for datastorage..user_qc_jb.costtime
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    public void setCosttime(String costtime) {
        this.costtime = costtime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column datastorage..user_qc_jb.memo
     *
     * @return the value of datastorage..user_qc_jb.memo
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column datastorage..user_qc_jb.memo
     *
     * @param memo the value for datastorage..user_qc_jb.memo
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    public void setMemo(String memo) {
        this.memo = memo;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column datastorage..user_qc_jb.adddate
     *
     * @return the value of datastorage..user_qc_jb.adddate
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    public String getAdddate() {
        return adddate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column datastorage..user_qc_jb.adddate
     *
     * @param adddate the value for datastorage..user_qc_jb.adddate
     *
     * @abatorgenerated Sat May 03 17:58:42 CST 2014
     */
    public void setAdddate(String adddate) {
        this.adddate = adddate;
    }

	public UserQcJb(Integer id, Integer userid, Integer companycode,
			String stardate, String enddate, String starttime, String endtime,
			String costtime, String memo, String adddate) {
		super();
		this.id = id;
		this.userid = userid;
		this.companycode = companycode;
		this.stardate = stardate;
		this.enddate = enddate;
		this.starttime = starttime;
		this.endtime = endtime;
		this.costtime = costtime;
		this.memo = memo;
		this.adddate = adddate;
	}
    
}