package com.example.model;

public class UserFee {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column datastorage..user_fee.id
     *
     * @abatorgenerated Sat May 03 19:12:45 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column datastorage..user_fee.userid
     *
     * @abatorgenerated Sat May 03 19:12:45 CST 2014
     */
    private Integer userid;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column datastorage..user_fee.companycode
     *
     * @abatorgenerated Sat May 03 19:12:45 CST 2014
     */
    private Integer companycode;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column datastorage..user_fee.projectname
     *
     * @abatorgenerated Sat May 03 19:12:45 CST 2014
     */
    private String projectname;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column datastorage..user_fee.address
     *
     * @abatorgenerated Sat May 03 19:12:45 CST 2014
     */
    private String address;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column datastorage..user_fee.applymoney
     *
     * @abatorgenerated Sat May 03 19:12:45 CST 2014
     */
    private String applymoney;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column datastorage..user_fee.applytype
     *
     * @abatorgenerated Sat May 03 19:12:45 CST 2014
     */
    private String applytype;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column datastorage..user_fee.applaytime
     *
     * @abatorgenerated Sat May 03 19:12:45 CST 2014
     */
    private String applaytime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column datastorage..user_fee.memo
     *
     * @abatorgenerated Sat May 03 19:12:45 CST 2014
     */
    private String memo;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column datastorage..user_fee.adddate
     *
     * @abatorgenerated Sat May 03 19:12:45 CST 2014
     */
    private String adddate;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column datastorage..user_fee.id
     *
     * @return the value of datastorage..user_fee.id
     *
     * @abatorgenerated Sat May 03 19:12:45 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column datastorage..user_fee.id
     *
     * @param id the value for datastorage..user_fee.id
     *
     * @abatorgenerated Sat May 03 19:12:45 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column datastorage..user_fee.userid
     *
     * @return the value of datastorage..user_fee.userid
     *
     * @abatorgenerated Sat May 03 19:12:45 CST 2014
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column datastorage..user_fee.userid
     *
     * @param userid the value for datastorage..user_fee.userid
     *
     * @abatorgenerated Sat May 03 19:12:45 CST 2014
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column datastorage..user_fee.companycode
     *
     * @return the value of datastorage..user_fee.companycode
     *
     * @abatorgenerated Sat May 03 19:12:45 CST 2014
     */
    public Integer getCompanycode() {
        return companycode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column datastorage..user_fee.companycode
     *
     * @param companycode the value for datastorage..user_fee.companycode
     *
     * @abatorgenerated Sat May 03 19:12:45 CST 2014
     */
    public void setCompanycode(Integer companycode) {
        this.companycode = companycode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column datastorage..user_fee.projectname
     *
     * @return the value of datastorage..user_fee.projectname
     *
     * @abatorgenerated Sat May 03 19:12:45 CST 2014
     */
    public String getProjectname() {
        return projectname;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column datastorage..user_fee.projectname
     *
     * @param projectname the value for datastorage..user_fee.projectname
     *
     * @abatorgenerated Sat May 03 19:12:45 CST 2014
     */
    public void setProjectname(String projectname) {
        this.projectname = projectname;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column datastorage..user_fee.address
     *
     * @return the value of datastorage..user_fee.address
     *
     * @abatorgenerated Sat May 03 19:12:45 CST 2014
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column datastorage..user_fee.address
     *
     * @param address the value for datastorage..user_fee.address
     *
     * @abatorgenerated Sat May 03 19:12:45 CST 2014
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column datastorage..user_fee.applymoney
     *
     * @return the value of datastorage..user_fee.applymoney
     *
     * @abatorgenerated Sat May 03 19:12:45 CST 2014
     */
    public String getApplymoney() {
        return applymoney;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column datastorage..user_fee.applymoney
     *
     * @param applymoney the value for datastorage..user_fee.applymoney
     *
     * @abatorgenerated Sat May 03 19:12:45 CST 2014
     */
    public void setApplymoney(String applymoney) {
        this.applymoney = applymoney;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column datastorage..user_fee.applytype
     *
     * @return the value of datastorage..user_fee.applytype
     *
     * @abatorgenerated Sat May 03 19:12:45 CST 2014
     */
    public String getApplytype() {
        return applytype;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column datastorage..user_fee.applytype
     *
     * @param applytype the value for datastorage..user_fee.applytype
     *
     * @abatorgenerated Sat May 03 19:12:45 CST 2014
     */
    public void setApplytype(String applytype) {
        this.applytype = applytype;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column datastorage..user_fee.applaytime
     *
     * @return the value of datastorage..user_fee.applaytime
     *
     * @abatorgenerated Sat May 03 19:12:45 CST 2014
     */
    public String getApplaytime() {
        return applaytime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column datastorage..user_fee.applaytime
     *
     * @param applaytime the value for datastorage..user_fee.applaytime
     *
     * @abatorgenerated Sat May 03 19:12:45 CST 2014
     */
    public void setApplaytime(String applaytime) {
        this.applaytime = applaytime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column datastorage..user_fee.memo
     *
     * @return the value of datastorage..user_fee.memo
     *
     * @abatorgenerated Sat May 03 19:12:45 CST 2014
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column datastorage..user_fee.memo
     *
     * @param memo the value for datastorage..user_fee.memo
     *
     * @abatorgenerated Sat May 03 19:12:45 CST 2014
     */
    public void setMemo(String memo) {
        this.memo = memo;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column datastorage..user_fee.adddate
     *
     * @return the value of datastorage..user_fee.adddate
     *
     * @abatorgenerated Sat May 03 19:12:45 CST 2014
     */
    public String getAdddate() {
        return adddate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column datastorage..user_fee.adddate
     *
     * @param adddate the value for datastorage..user_fee.adddate
     *
     * @abatorgenerated Sat May 03 19:12:45 CST 2014
     */
    public void setAdddate(String adddate) {
        this.adddate = adddate;
    }

	public UserFee(Integer id, Integer userid, Integer companycode,
			String projectname, String address, String applymoney,
			String applytype, String applaytime, String memo, String adddate) {
		super();
		this.id = id;
		this.userid = userid;
		this.companycode = companycode;
		this.projectname = projectname;
		this.address = address;
		this.applymoney = applymoney;
		this.applytype = applytype;
		this.applaytime = applaytime;
		this.memo = memo;
		this.adddate = adddate;
	}
    
    
}