package com.example.model;

public class UserCustomerBf {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column datastorage..user_customer_bf.id
     *
     * @abatorgenerated Sun Apr 27 20:07:51 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column datastorage..user_customer_bf.userid
     *
     * @abatorgenerated Sun Apr 27 20:07:51 CST 2014
     */
    private Integer userid;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column datastorage..user_customer_bf.companyid
     *
     * @abatorgenerated Sun Apr 27 20:07:51 CST 2014
     */
    private Integer companyid;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column datastorage..user_customer_bf.customerid
     *
     * @abatorgenerated Sun Apr 27 20:07:51 CST 2014
     */
    private Integer customerid;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column datastorage..user_customer_bf.addtime
     *
     * @abatorgenerated Sun Apr 27 20:07:51 CST 2014
     */
    private String addtime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column datastorage..user_customer_bf.bz
     *
     * @abatorgenerated Sun Apr 27 20:07:51 CST 2014
     */
    private String bz;

    
    
    public UserCustomerBf(Integer id, Integer userid, Integer companyid,
			Integer customerid, String addtime, String bz) {
		super();
		this.id = id;
		this.userid = userid;
		this.companyid = companyid;
		this.customerid = customerid;
		this.addtime = addtime;
		this.bz = bz;
	}

	/**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column datastorage..user_customer_bf.id
     *
     * @return the value of datastorage..user_customer_bf.id
     *
     * @abatorgenerated Sun Apr 27 20:07:51 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column datastorage..user_customer_bf.id
     *
     * @param id the value for datastorage..user_customer_bf.id
     *
     * @abatorgenerated Sun Apr 27 20:07:51 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column datastorage..user_customer_bf.userid
     *
     * @return the value of datastorage..user_customer_bf.userid
     *
     * @abatorgenerated Sun Apr 27 20:07:51 CST 2014
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column datastorage..user_customer_bf.userid
     *
     * @param userid the value for datastorage..user_customer_bf.userid
     *
     * @abatorgenerated Sun Apr 27 20:07:51 CST 2014
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column datastorage..user_customer_bf.companyid
     *
     * @return the value of datastorage..user_customer_bf.companyid
     *
     * @abatorgenerated Sun Apr 27 20:07:51 CST 2014
     */
    public Integer getCompanyid() {
        return companyid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column datastorage..user_customer_bf.companyid
     *
     * @param companyid the value for datastorage..user_customer_bf.companyid
     *
     * @abatorgenerated Sun Apr 27 20:07:51 CST 2014
     */
    public void setCompanyid(Integer companyid) {
        this.companyid = companyid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column datastorage..user_customer_bf.customerid
     *
     * @return the value of datastorage..user_customer_bf.customerid
     *
     * @abatorgenerated Sun Apr 27 20:07:51 CST 2014
     */
    public Integer getCustomerid() {
        return customerid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column datastorage..user_customer_bf.customerid
     *
     * @param customerid the value for datastorage..user_customer_bf.customerid
     *
     * @abatorgenerated Sun Apr 27 20:07:51 CST 2014
     */
    public void setCustomerid(Integer customerid) {
        this.customerid = customerid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column datastorage..user_customer_bf.addtime
     *
     * @return the value of datastorage..user_customer_bf.addtime
     *
     * @abatorgenerated Sun Apr 27 20:07:51 CST 2014
     */
    public String getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column datastorage..user_customer_bf.addtime
     *
     * @param addtime the value for datastorage..user_customer_bf.addtime
     *
     * @abatorgenerated Sun Apr 27 20:07:51 CST 2014
     */
    public void setAddtime(String addtime) {
        this.addtime = addtime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column datastorage..user_customer_bf.bz
     *
     * @return the value of datastorage..user_customer_bf.bz
     *
     * @abatorgenerated Sun Apr 27 20:07:51 CST 2014
     */
    public String getBz() {
        return bz;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column datastorage..user_customer_bf.bz
     *
     * @param bz the value for datastorage..user_customer_bf.bz
     *
     * @abatorgenerated Sun Apr 27 20:07:51 CST 2014
     */
    public void setBz(String bz) {
        this.bz = bz;
    }
}